TITLE = {'conf/soda/Li08': 'Estimators and tail bounds for dimension reduction in l{$\\alpha$}; ({$0 < \\alpha \le 2$}) using stable random projections'
        }

CONFERENCE_LOCATIONS = {
     '':{}
    ,'icdcs':       {2002: ('Vienna', 'jul')
                    ,2001: ('Phoenix', 'apr')
                    ,2000: ('Taipei', 'apr')
                    ,1999: ('AustinTX', 'jun')
                    ,1998: ('Amsterdam', 'may')
                    ,1997: ('Baltimore', 'may')
                    ,1996: ('HongKong', 'may')
                    ,1995: ('Vancouver', 'may')
                    ,1994: ('Poznan', 'jun')
                    ,1993: ('Pittsburgh', 'may')
                    ,1992: ('Yokohama', 'jun')
                    ,1989: ('NewportBeach', 'jun')
                    ,1988: ('SanJose', 'jun')
                    ,1987: ('WestBerlin', 'sep')
                    ,1986: ('CambridgeMA', 'may')
                    ,1985: ('Denver', 'may')
                    ,1984: ('SanFrancisco', 'may')
                    ,1981: ('Paris', 'apr')
                    }
    ,'ipps':        {1993: ('NewportBeach', 'apr')
                    ,1991: ('Anaheim', 'apr')
                    }
    ,'sigcomm':     {1997: ('Cannes', 'sep')
                    ,1996: ('Stanford', 'aug')
                    ,1995: ('CambridgeMA', 'aug')
                    ,1994: ('London', 'aug')
                    ,1993: ('SF', 'sep')
                    ,1992: ('Baltimore', 'aug')
                    ,1991: ('Zurich', 'sep')
                    ,1990: ('Philadelphia', 'sep')
                    ,1989: ('Austin', 'sep')
                    ,1988: ('Stanford', 'aug')
                    ,1985: ('BC', 'sep')
                    }
    ,'sosp':        {2001: ('Banff', 'oct')
                    ,1999: ('KiawahIsland', 'dec')
                    ,1997: ('SaintMalo', 'oct')
                    ,1995: ('CopperMountain', 'dec')
                    ,1993: ('Asheville', 'oct')
                    ,1991: ('PacificGrove', 'oct')
                    ,1989: ('LitchfieldPark', 'dec')
                    ,1987: ('Austin', 'nov')
                    ,1985: ('OrcasIsland', 'dec')
                    ,1983: ('BrettonWoods', 'oct')
                    ,1981: ('PacificGrove', 'dec')
                    ,1979: ('PacificGrove', 'dec')
                    ,1977: ('WestLafayette', 'nov')
                    ,1975: ('Austin', 'nov')
                    ,1973: ('YorktownHeights', 'oct')
                    ,1971: ('PaloAlto', 'oct')
                    ,1969: ('Princeton', 'oct')
                    ,1967: ('Gatlinburg', 'may')
                    }
    ,'sigmod':      {2001: ('SantaBarbera', 'may')
                    ,1987: ('SanFrancisco', 'may')
                    ,1984: ('Boston', 'jun')
                    ,1983: ('SanJose', 'may')
                    }
    }
