BLACKLIST = set([
'abstract',
'abstract only',
'a. m. turing award lecture',
'an announcement',
'an extended abstract',
'a preliminary version',
'avstract',
'awarded best paper!',
'awarded best paper',
'awarded best student paper!',
'awarded best student paper',
'best paper',
'brief announcement',
'brief announement',
'detailed abstract',
'extenced abstract',
'extended abstract',
'extended anstract',
'extended astract',
'extended summary',
'invited address',
'panel',
'panel session, abstract only',
'panel session - title only',
'panel session, title only',
'panel statement',
'pearl',
'podc 1984 invited address',
'poster',
'poster abstract',
'preliminary report',
'preliminary reports',
'preliminary version',
'short abstract',
'shortened version',
'summary',
'working paper',
'work in progress, abstract',
])


WHITELIST = set([
'0, 1',
'1, 2',
'1 + beta',
'1+, varepsilon;, beta',
'1 + epsilon',
'2 + epsilon',
'2k',
'almost',
'alpha, beta',
'and beyond',
'and other',
'a polynomial algorithm for 3-compatible colouring and the stubborn list partition problem',
'applications of comparative physical maps in molecular evolution',
'cost',
'cycles, and partitions',
'dctcp',
'deterministic',
'dsdv',
'dynamic',
'expected time',
'fitting distances by tree metrics',
'googling the internet',
'hyper',
'im',
'incremental',
'indeterministic',
'in java',
'max, min',
'mis',
'more',
'networks of workstations',
'n log n',
'optimal',
'or how to turn ideas into live systems in a breeze',
'or, programs from outer space',
'or repetitive consensus',
'poly',
'really',
'repeated',
's',
'satnet',
'semi',
'sharqfec',
'some',
'some preprocessing required',
'storage',
'sundr',
'travelocity-based detouring',
u'1+epsilon',
'un',
'unproven',
'unweighted',
'very',
'weakly',
'without matrix multiplication',
'without powerdomains',
])

TRANSLATE = {'ISDN, panel': 'ISDN'}
