BLACKLIST = set([
'abridged version',
'abstract',
'abstract of invited tutorial',
'abstract only',
'a. m. turing award lecture',
'an announcement',
'an extended abstract',
'a preliminary version',
'avstract',
'awarded best paper!',
'awarded best paper',
'awarded best student paper!',
'awarded best student paper',
'best paper',
'brief announcement',
'brief announement',
'demo',
'demonstration description',
'detailed abstract',
'experience paper',
'extenced abstract',
'extended abstract',
'extended abstracts',
'extended announcement',
'extended anstract',
'extended astract',
'extended summary',
'invited address',
'invited paper',
'keynote address',
'panel',
'panel abstract',
'panel session, abstract only',
'panel session - title only',
'panel session, title only',
'panel statement',
'partial report',
'pearl',
'podc 1984 invited address',
'poster',
'poster abstract',
'preliminary abstract',
'preliminary draught',
'preliminary report',
'preliminary reports',
'preliminary version',
'short abstract',
'shortened version',
'summary',
'tutorial',
'working paper',
'work in progress, abstract',
])

WHITELIST = set([
'!=',
'0, 1',
'1, 2',
'1 + beta',
'1 + eps',
'1 + epsilon',
'1+, varepsilon;, beta',
'2 + epsilon',
'2+epsilon',
'2k',
'acyclic',
'almost',
'alpha, beta',
'and beyond',
'and beyond?',
'and everthing in between',
'and other',
'and pretty good for quantum as well',
'and safety',
'and trusting no one',
'a polynomial algorithm for 3-compatible colouring and the stubborn list partition problem',
'applications of comparative physical maps in molecular evolution',
'bsr',
'btx',
'byzantine agreement on uniformly random values',
'commerce edition',
'connected',
'cost',
'cycles, and partitions',
'data',
'database',
'dctcp',
'de',
'deadlock detection',
'demo abstract',
'deterministic',
'dis',
'disco',
'dsdv',
'dynamic',
'epsilon, delta',
'esair',
'expected time',
'fairly',
'fitting distances by tree metrics',
'for high-concurrency servers',
'for vlsi',
'googling the internet',
'h-k',
'hms',
'hyper',
'im',
'in',
'in cournot competition',
'incremental',
'indeterministic',
'in java',
'internals overview',
'jsq',
'<= k',
'k, r',
'lbc',
'ldl',
'ldl1',
'learning a string',
'learning a string',
'log ^c n',
'log n',
"maier's o-logic revisited",
'max, min',
'meta',
'mis',
'mod p - mod m',
'more',
'multi',
'natural',
'n, d',
'nearly',
'networks of workstations',
'n log n',
'non',
'not',
'not a privilege',
'object database and environment',
'only',
'optimal',
'or, business processes for database researchers',
'or how to turn ideas into live systems in a breeze',
'or, programs from outer space',
'or repetitive consensus',
'or, routing issues in mpls',
'or, why mazes are easier to search than graphs',
'output',
'parallel',
'part i',
'part ii',
'part i: the architecture',
'physical design tuning',
'poly',
'polynomial algorithm for genomic distance problem',
'probably',
"proc. sigmod'03",
'psa',
'raid',
'really',
'repeated',
'rladsms',
's',
'satnet',
'semi',
'sharqfec',
'some',
'some preprocessing required',
'spo protocol',
's, t',
'standard',
'storage',
'stream-enabled',
'sundr',
't + 1',
'the odds are on his side',
'travelocity-based detouring',
u'1+epsilon',
u'1+\u03ad',
u'1 + \u03b5',
'un',
'unproven',
'unweighted',
'very',
'vlsi',
'wavelength',
'weakly',
'without matrix multiplication',
'without powerdomains',
'workshop rewiew',
])

TRANSLATE = {'ISDN, panel': 'ISDN'}
