BLACKLIST = set([
'abridged version',
'abstract',
'abstract of invited tutorial',
'abstract only',
"acm president's letter",
'a. m. turing award lecture',
'an announcement',
'an extended abstract',
'a preliminary version',
'avstract',
'awarded best paper!',
'awarded best paper',
'awarded best student paper!',
'awarded best student paper',
'best paper',
'brief announcement',
'brief announement',
'demo',
'demonstration description',
'detailed abstract',
'draft',
'experience paper',
'extenced abstract',
'extended abstract',
'extended abstracts',
'extended announcement',
'extended anstract',
'extended astract',
'extended summary',
'indroduction to the special section on logic programming',
'interview',
'introduction to the special issue',
'introduction to the special section',
'intruduction to the special section',
'invited address',
'invited paper',
'keynote address',
'panel',
'panel abstract',
'panel session, abstract only',
'panel session - title only',
'panel session, title only',
'panel statement',
'partial report',
'pearl',
'podc 1984 invited address',
'poster',
'poster abstract',
'preliminary abstract',
'preliminary draught',
'preliminary report',
'preliminary reports',
'preliminary version',
'remarks',
'report of the jtec panel',
'reprint',
'short abstract',
'shortened version',
'summary',
"surveyors' forum",
'turing award lecture',
'tutorial',
'working paper',
'work in progress, abstract',
])

WHITELIST = set([
'!=',
'0, 1',
'1, 2',
'1, 342 times and counting',
'1600 cpi, phase encoded',
'1982',
'1 + beta',
'1 + eps',
'1 + epsilon',
'1+, varepsilon;, beta',
'2 + epsilon',
'2+epsilon',
'2k',
'800 cpi, nrzi',
'9 track-200 and 800 cpi, nrzi and 1600 cpi, p.e.',
'a case of error reporting system',
'acsii',
'active suspension',
'acyclic',
'algorithm a433',
'algorithm a438',
'almost',
'alpha, beta',
'and a letter',
'and beyond?',
'and beyond',
'and darwinian',
'and everthing in between',
'and everything else',
'and how flash memory changes the rules',
'and how not to',
"and how they're sometimes found",
'and mistrust',
'and other',
'and pretty good for quantum as well',
'and safety',
'and the sesame street syndrome',
'and trusting no one',
'a polynomial algorithm for 3-compatible colouring and the stubborn list partition problem',
'applications of comparative physical maps in molecular evolution',
'april 1984 special section',
'a usaai',
'bsr',
'btx',
'byzantine agreement on uniformly random values',
'commerce edition',
'components + patterns',
'computer',
'connected',
'console operator proficiency examination',
'cosers',
'cost',
'creation and use',
'cycles, and partitions',
'data',
'database',
'dctcp',
'de',
'deadlock detection',
'demo abstract',
'deterministic',
'dis',
'disco',
'dsdv',
'dynamic',
'early and often?',
'else',
'epsilon, delta',
'esair',
'even and odd orders',
'even order',
'expected time',
'fairly',
'ferrite',
'+-f(+-f(...+-f(x)...))',
'fitting distances by tree metrics',
'for high-concurrency servers',
'for vlsi',
'gier algol',
'googling the internet',
'gradually',
'h-k',
'hms',
'hyper',
'ii',
'im',
'in',
'in cournot competition',
'incremental',
'indeterministic',
'in java',
'intermittent assertions in proving program correctness',
'internals overview',
'intervals',
'jsq',
'june 1962',
'<= k',
'k, r',
'lbc',
'ldl',
'ldl1',
'learning a string',
'log ^c n',
'log n',
"maier's o-logic revisited",
'max, min',
'meta',
'mis',
'mod p - mod m',
'more',
'multi',
'natural',
'n, d',
'nearly',
'networks of workstations',
'n log n',
'non',
'not',
'not a privilege',
'object database and environment',
'odd and even orders',
'odd and, even orders',
'odd order',
'on behalf of john cocke',
'online',
'only',
'optimal',
'oracle curve plotter',
'or, business processes for database researchers',
'or how to turn ideas into live systems in a breeze',
'or not',
'or, programs from outer space',
'or repetitive consensus',
'or, routing issues in mpls',
'or towards a standard ada subset',
'or, why mazes are easier to search than graphs',
'output',
'over',
'parallel',
'part 1',
'part 2',
'part i',
'part ii',
'part i: the architecture',
'physical design tuning',
'poly',
'polynomial algorithm for genomic distance problem',
'probably',
"proc. sigmod'03",
'psa',
'raid',
're',
'really',
'rectangular matrices',
'remark on algorithms 352, 385, 392',
'repeated',
'rladsms',
'rome',
's',
'satnet',
'sba',
'sembegs',
'semi',
'sharqfec',
'some',
'some preprocessing required',
'source',
'spo protocol',
's, t',
'standard',
'storage',
'stream-enabled',
'sundr',
't + 1',
'talking with julian gosper, jean-luc agathos, richard rutter, and terry coatta',
'the choice of decimal or binary representation',
'the odds are on his side',
'the vasa',
'travelocity-based detouring',
'tribute, jonathan b. postel 1943-1998',
u'1+epsilon',
u'1+\u03ad',
u'1 + \u03b5',
'un',
'unproven',
'unto',
'unweighted',
'very',
'viewpoint',
'vlsi',
'wavelength',
'weakly',
'what once was',
'without conditional statements',
'without matrix multiplication',
'without powerdomains',
'workshop rewiew',
'wyxiwyg',
'x',
])

TRANSLATE = {'ISDN, panel': 'ISDN'}
